# Generated by Django 4.2.4 on 2023-08-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='some_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
