# Generated by Django 4.2.4 on 2023-08-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_some_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='some_name',
        ),
    ]
